# Generated by Django 4.2.7 on 2023-11-16 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields.related


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sourcetype', models.CharField(max_length=255)),
                ('processingtype', models.CharField(max_length=255)),
                ('parameterid', models.IntegerField()),
                ('parametername', models.CharField(max_length=255)),
                ('parametertable', models.CharField(max_length=255)),
                ('sharedmemoryid', models.IntegerField()),
                ('isactive', models.BooleanField()),
            ],
            options={
                'db_table': 'hierarchy"."datasource',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Login_User_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_name', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mode_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_name', models.CharField(max_length=155)),
                ('mode_description', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project_User_Mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=155)),
                ('project_description', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('logo', models.TextField()),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('user_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Previlege_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('description', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('visibility', models.BooleanField(default=True)),
                ('mode_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ncarp_lens_app.mode_details')),
            ],
        ),
        migrations.CreateModel(
            name='Page_User_Mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=155)),
                ('page_description', models.CharField(max_length=255)),
                ('access_to', models.CharField(max_length=155)),
                ('background', models.CharField(max_length=155)),
                ('layout', models.CharField(max_length=155)),
                ('data', models.JSONField(default=None)),
                ('is_active', models.BooleanField(default=True)),
                ('project_user_mapping', models.ForeignKey(on_delete=django.db.models.fields.related.ForeignKey, to='ncarp_lens_app.project_user_mapping')),
            ],
        ),
    ]
